### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by bwildenhain** [cceh/CMDI-Maker#2]
According to docs/poster.pdf your software is open sourced. However, a lot of files do not contain any copyright information. Thus those files probably cannot be legally used in countries having copyright laws. Would it be possible to somewhere document which files are licensed according to which license terms? There are some suggestions how to do this on https://help.github.com/articles/open-source-licensing/

**Comment by polyrainbow** [comment]
Thanks for the input. I've added a LICENSE.md to the repository. Most of the source files had a license header anyway. Are you aware of any files that need fixing additionally?

**Comment by polyrainbow** [comment]
Closing this issue because the licensing status should now be clear after commit 8f3943ffae932a957b0bb947e664af9157ff18a7
Please reopen if I missed something important.
