### ISSUE TITLE
CMDI Maker: signal environment in Interface

### ISSUE THREAD

**Issue by MigRam** [cceh/CMDI-Maker#7]
It would be great if the user knows the environment he is currently working.

**Comment by polyrainbow** [comment]
An idea would be to use the space beneath the app title for this:

![environment indication](https://cloud.githubusercontent.com/assets/5648131/17017900/a524a286-4f35-11e6-9901-8f4b8f8bc4a5.png)

**Comment by MigRam** [comment]
feedback see pull requests #8, #9

**Comment by jblumtritt** [comment]
![cmdi-maker-environment-name-and-version](https://cloud.githubusercontent.com/assets/3205396/17174910/06c27224-5405-11e6-87c0-9010b17a975f.jpg)

cool.
Beta: zeigt jetzt Name und Version des Environments.  
Ich würde lieber NUR den Namen dort oben anzeigen.
eldp, v2.17 als debugging- und support-information ist aber auch interessant. Allerdings würde ich es lieber woander platzieren, wo es weniger auffällig ist. z.B.
- rechts unten auf der lila Abschlussleiste
- oder rechts oben unter dem Burger

**Comment by MigRam** [comment]
resolved #10 #11 #12

**Comment by jblumtritt** [comment]
beta: 
![cmdi-maker-environment-anzeigen](https://cloud.githubusercontent.com/assets/3205396/17293022/fce4df48-57ed-11e6-8110-ee9fb6c99e97.jpg)

nice.
maybe we could add the version number to the pop-up message.
"you are using ELDP profile v 2.17"
